name: Lean_LEDE_N1

on:
#  schedule:
#    - cron: 0 6 1/3 * *
  repository_dispatch:
    types: run
    
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: [ubuntu-18.04]
    if: github.event_name == 'schedule' || github.event.action == 'run'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install depends
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone Lean's openwrt
        run: |
          git clone https://github.com/coolsnowwolf/lede

      - name: Install feeds
        run: |
          cd lede
          
          git clone https://github.com/tuanqing/lede-mod
          git clone https://github.com/tuanqing/install-program package/install-program
          svn co https://github.com/Lienol/openwrt-package/trunk/lienol/luci-theme-bootstrap-mod package/luci-theme-bootstrap-mod

          git apply lede-mod/lede/*.patch
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          git apply lede-mod/luci/*.patch --directory=feeds/luci
          git apply lede-mod/bootstrap/*.patch --directory=package/luci-theme-bootstrap-mod

      - name: Make config
        run: |
          cd lede

          cat > .config << EOF
          CONFIG_TARGET_armvirt=y
          CONFIG_TARGET_armvirt_64=y
          CONFIG_TARGET_armvirt_64_DEVICE_Phicomm-n1=y
          CONFIG_BRCMFMAC_SDIO=y
          CONFIG_PACKAGE_luci-app-haproxy-tcp=y
          # CONFIG_UnblockNeteaseMusic_NodeJS is not set
          EOF

          make defconfig
          ./scripts/feeds update -a
          cat .config

      - name: Compile openwrt
        run: |
          cd lede
          make download -j8
          make -j$(nproc) || make -j1 V=s

      - name: Build firmware
        run: |
          cp lede/bin/targets/*/*/*.tar.gz ./openwrt
          sudo ./make -d
          cp lede/.config out/config.seed

          cd out
          i=0
          kernels=("4.18.7" "4.19.106" "5.4.43")
          for x in ${kernels[*]}; do
            cd $x
            filename=$(ls)
            filename=${filename%.*}
            gzip *.img
            cd ../
            echo "::set-env name=firmware_$((++i))::$filename"
          done

      - name: Upload firmware @ kernel 4.18.7
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.firmware_1 }}
          path: out/4.18.7
      
      - name: Upload firmware @ kernel 4.19.106
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.firmware_2 }}
          path: out/4.19.106
      
      - name: Upload firmware @ kernel 5.4.43
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.firmware_3 }}
          path: out/5.4.43

      - name: Upload config file
        uses: actions/upload-artifact@main
        with:
          name: config
          path: out/config.seed
